command: python train.py --data ./data/fld.yaml --weights '' --cfg ./models/yolov5m.yaml --batch-size 40 --logdir /storag    e/sjiphrwm/ --device 0 &> /storage/sjiphrwm/train_yolov5m_fld.log
container: nvcr.io/nvidia/pytorch:19.04-py3
machineType: K80
modelPath: /storage/sjiphrwm
modelType: Pytorch
name: yolov5
workspace: 'https://github.com/macshkim/hara_yolov5.git'

