version: 2

workflows:
  single-node:
    steps:
      -
        name: "single-node"
        command: experiment.run_single_node
        params:
          command: nvidia-smi
          container: nvcr.io/nvidia/pytorch:19.04-py3
          command: "python train.py --data ./data/fld.yaml --weights '' --cfg ./models/yolov5m.yaml --batch-size 40 --logdir ./runs/ --device 0 &> train_yolov5m_fld.log"
          machineType: "K80"
